name: test-action
on: [push]
jobs:
  unit-test:
    runs-on: alpine
    steps:
      - uses: actions/checkout@v2
      - uses: action/setup-go@v2
        with:
          go-version: '^1.17'
      - run: go test -run ^TestSum$ github.com/Pyt45/workflow-testing.git/utils 